INSERT INTO ROLE (RIGHT) VALUES ('ROLE_USER');

INSERT INTO USER (USERNAME, PIC, EMAIL, FK_ROLE_ID) VALUES ('Mathew', NULL, 'MATHEW@EMAIL.COM', 1);
INSERT INTO USER (USERNAME, PIC, EMAIL, FK_ROLE_ID) VALUES ('Ann', NULL, 'ANN@EMAIL.COM', 1);
INSERT INTO USER (USERNAME, PIC, EMAIL, FK_ROLE_ID) VALUES ('Bob', NULL, 'BOB@EMAIL.COM', 1);
INSERT INTO USER (USERNAME, PIC, EMAIL, FK_ROLE_ID) VALUES ('Sam', NULL, 'SAM@EMAIL.COM', 1);
INSERT INTO USER (USERNAME, PIC, EMAIL, FK_ROLE_ID) VALUES ('John', NULL, 'JOHN@EMAIL.COM', 1);

INSERT INTO CATEGORY (CATEGORY_ID, NAME) VALUES (1, 'CLOTHS');

INSERT INTO CREDENTIALS (FK_USER_ID, PASS) VALUES (1, '12345');
INSERT INTO CREDENTIALS (FK_USER_ID, PASS) VALUES (1, '12345');
INSERT INTO CREDENTIALS (FK_USER_ID, PASS) VALUES (2, '7659');

INSERT INTO QUESTIONS (DESCRIPTION, TEXT, FK_CATEGORY_ID, FK_USER_ID, DATE) VALUES ('WHERES MY PANTS','Wheres my pants?', 1, 1, '2016-08-29');


